baseURL = "/"
title   = "Leon"

DefaultContentLanguage = "en"
theme = "hello-friend-ng"

pygmentsCodefences = false
pygmentsUseClasses = false

rssLimit  = 50  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

publishDir   = "public"

buildDrafts  = false
buildFuture  = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "localleon"
  
[blackfriday]
  hrefTargetBlank = true
  
[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Personal Homepage of localleon"
  keywords = "homepage,blog,projects"
  images = [""]

  homeSubtitle = "Welcome to my personal homepage"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  [params.logo]
    logoText     = "$ cd /web/"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "email"
    url  = "mailto:me@lrau.systems"

  [[params.social]]
    name = "github"
    url  = "https://github.com/localleon"

[languages]
  [languages.en]
    subtitle  = "Homepage & Blog"
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [languages.de]
    subtitle  = "Homepage & Blog"
    weight    = 2
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Articles"
    url        = "posts/"
  [[menu.main]]
    identifier = "works"
    name       = "Works"
    url        = "works/"
