name: Build Hugo Site & Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.91.2"
          extended: true

      - name: Build
        run: hugo --minify

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 sync ./public s3://lrau-page --acl public-read --delete

      - name: Invalidate Cloudfront Distribution Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E35M7KA9RKX114 --paths "/"
